service: condominium-management-server
# app and org for use with dashboard.serverless.com
app: condominium-management-server-app
org: desouzaricardoc

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

functions:
  getApartments:
    handler: handler.getAllApartments
    events:
      - http:
          path: apartments
          method: get
          cors: true

plugins:
  - serverless-offline