service: condominium-management-server
# app and org for use with dashboard.serverless.com
app: condominium-management-server-app
org: desouzaricardoc

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
