service: condominium-management-server
# app and org for use with dashboard.serverless.com
app: condominium-management-server-app
org: desouzaricardoc

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

# the functions section, they are linked to the exported functions on "handler.js"
# the paths all follow the naming convention of a standard REST API.
# they will be used by the "serverless" framework to trigger the AWS Lambda functions
functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

  playground:
    handler: graphql.playgroundHandler
    events:
      - http:
          path: playground
          method: get
          cors: true

plugins:
  - serverless-offline